/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTournamentsRouteImport } from './routes/_authenticated/tournaments'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedPlayersRouteImport } from './routes/_authenticated/players'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTournamentsRoute =
  AuthenticatedTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersRoute = AuthenticatedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/tournaments': typeof AuthenticatedTournamentsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/tournaments': typeof AuthenticatedTournamentsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/players': typeof AuthenticatedPlayersRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/tournaments': typeof AuthenticatedTournamentsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inventory'
    | '/players'
    | '/reservations'
    | '/sales'
    | '/tournaments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/inventory'
    | '/players'
    | '/reservations'
    | '/sales'
    | '/tournaments'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/inventory'
    | '/_authenticated/players'
    | '/_authenticated/reservations'
    | '/_authenticated/sales'
    | '/_authenticated/tournaments'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tournaments': {
      id: '/_authenticated/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof AuthenticatedTournamentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedPlayersRoute: typeof AuthenticatedPlayersRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedTournamentsRoute: typeof AuthenticatedTournamentsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedPlayersRoute: AuthenticatedPlayersRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedTournamentsRoute: AuthenticatedTournamentsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
