/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTournamentsRouteImport } from './routes/_authenticated/tournaments'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedPlayersRouteImport } from './routes/_authenticated/players'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedCoachesIndexRouteImport } from './routes/_authenticated/coaches/index'
import { Route as AuthenticatedInventorySalesLogRouteImport } from './routes/_authenticated/inventory/sales-log'
import { Route as AuthenticatedInventoryDashboardRouteImport } from './routes/_authenticated/inventory/dashboard'
import { Route as AuthenticatedCoachesClassesRouteImport } from './routes/_authenticated/coaches/classes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTournamentsRoute =
  AuthenticatedTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersRoute = AuthenticatedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachesIndexRoute =
  AuthenticatedCoachesIndexRouteImport.update({
    id: '/coaches/',
    path: '/coaches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySalesLogRoute =
  AuthenticatedInventorySalesLogRouteImport.update({
    id: '/inventory/sales-log',
    path: '/inventory/sales-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryDashboardRoute =
  AuthenticatedInventoryDashboardRouteImport.update({
    id: '/inventory/dashboard',
    path: '/inventory/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachesClassesRoute =
  AuthenticatedCoachesClassesRouteImport.update({
    id: '/coaches/classes',
    path: '/coaches/classes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/tournaments': typeof AuthenticatedTournamentsRoute
  '/coaches/classes': typeof AuthenticatedCoachesClassesRoute
  '/inventory/dashboard': typeof AuthenticatedInventoryDashboardRoute
  '/inventory/sales-log': typeof AuthenticatedInventorySalesLogRoute
  '/coaches/': typeof AuthenticatedCoachesIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/players': typeof AuthenticatedPlayersRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/tournaments': typeof AuthenticatedTournamentsRoute
  '/': typeof AuthenticatedIndexRoute
  '/coaches/classes': typeof AuthenticatedCoachesClassesRoute
  '/inventory/dashboard': typeof AuthenticatedInventoryDashboardRoute
  '/inventory/sales-log': typeof AuthenticatedInventorySalesLogRoute
  '/coaches': typeof AuthenticatedCoachesIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/players': typeof AuthenticatedPlayersRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/tournaments': typeof AuthenticatedTournamentsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/coaches/classes': typeof AuthenticatedCoachesClassesRoute
  '/_authenticated/inventory/dashboard': typeof AuthenticatedInventoryDashboardRoute
  '/_authenticated/inventory/sales-log': typeof AuthenticatedInventorySalesLogRoute
  '/_authenticated/coaches/': typeof AuthenticatedCoachesIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/players'
    | '/reservations'
    | '/tournaments'
    | '/coaches/classes'
    | '/inventory/dashboard'
    | '/inventory/sales-log'
    | '/coaches/'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/players'
    | '/reservations'
    | '/tournaments'
    | '/'
    | '/coaches/classes'
    | '/inventory/dashboard'
    | '/inventory/sales-log'
    | '/coaches'
    | '/inventory'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/players'
    | '/_authenticated/reservations'
    | '/_authenticated/tournaments'
    | '/_authenticated/'
    | '/_authenticated/coaches/classes'
    | '/_authenticated/inventory/dashboard'
    | '/_authenticated/inventory/sales-log'
    | '/_authenticated/coaches/'
    | '/_authenticated/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tournaments': {
      id: '/_authenticated/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof AuthenticatedTournamentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coaches/': {
      id: '/_authenticated/coaches/'
      path: '/coaches'
      fullPath: '/coaches/'
      preLoaderRoute: typeof AuthenticatedCoachesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/sales-log': {
      id: '/_authenticated/inventory/sales-log'
      path: '/inventory/sales-log'
      fullPath: '/inventory/sales-log'
      preLoaderRoute: typeof AuthenticatedInventorySalesLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/dashboard': {
      id: '/_authenticated/inventory/dashboard'
      path: '/inventory/dashboard'
      fullPath: '/inventory/dashboard'
      preLoaderRoute: typeof AuthenticatedInventoryDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coaches/classes': {
      id: '/_authenticated/coaches/classes'
      path: '/coaches/classes'
      fullPath: '/coaches/classes'
      preLoaderRoute: typeof AuthenticatedCoachesClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPlayersRoute: typeof AuthenticatedPlayersRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedTournamentsRoute: typeof AuthenticatedTournamentsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCoachesClassesRoute: typeof AuthenticatedCoachesClassesRoute
  AuthenticatedInventoryDashboardRoute: typeof AuthenticatedInventoryDashboardRoute
  AuthenticatedInventorySalesLogRoute: typeof AuthenticatedInventorySalesLogRoute
  AuthenticatedCoachesIndexRoute: typeof AuthenticatedCoachesIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPlayersRoute: AuthenticatedPlayersRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedTournamentsRoute: AuthenticatedTournamentsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCoachesClassesRoute: AuthenticatedCoachesClassesRoute,
  AuthenticatedInventoryDashboardRoute: AuthenticatedInventoryDashboardRoute,
  AuthenticatedInventorySalesLogRoute: AuthenticatedInventorySalesLogRoute,
  AuthenticatedCoachesIndexRoute: AuthenticatedCoachesIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
